import "./globals.css";
import Navbar from "@/component/Navbar";

export const metadata = {
  title: "Developers Roadmap",
  description:
    "A Developers Roadmap. Application is generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="bumblebee">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
