import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Developers Roadmap",
  description:
    "A Developers Roadmap. Application is generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="bumblebee">
      <body>
        <div>
          <Toaster />
        </div>
        {children}
      </body>
    </html>
  );
}
